### ISSUE TITLE
There's no Tango theme with a white background

### ISSUE THREAD

**Issue by mgedmin** [asciinema/asciinema-server#200]
My gnome-terminal uses the Tango colour palette, and has a white background (which is an upstream default).

I have selected the Tango theme in my profile settings, and I see my screencats show up with a dark background.  That doesn't matter too much for shell sessions, but vim gets misrendered badly:
![ekrano nuotrauka is 2015-09-10 12-06-46](https://cloud.githubusercontent.com/assets/159967/9784549/6e4b8fdc-57b4-11e5-82e1-28f175228d47.png)

Here's how it actually looks on my screen:
![ekrano nuotrauka is 2015-09-10 12-07-59](https://cloud.githubusercontent.com/assets/159967/9784578/9c0f0b92-57b4-11e5-98e2-d441b3f46772.png)

**Comment by sickill** [comment]
I did quick googling for Tango terminal theme and found this theme for various terminal emulators, all with dark background. Examples: https://wiki.archlinux.org/index.php/Xfce#Terminal_tango_color_theme and https://gist.github.com/menski/2176539#file-xresources-L24

Looks like there's no official "tango terminal theme", they're all based on "tango palette", and the author of gnome-terminal one chose light background (which seems to be less popular variation).

I'm fine with adding "Tango (light bg)" theme to asciinema, and rename current "Tango" to "Tango (dark bg)".

**Comment by mgedmin** [comment]
Sounds good to me!

**Comment by sickill** [comment]
I'm closing old issues. Please reopen if you still think this is a valuable feature worth maintaining.

**Comment by mgedmin** [comment]
I don't have the permission to reopen.  :(

**Comment by ku1ik** [comment]
asciinema CLI 3.0 (soon to be released) captures original terminal colors now, and the player renders them accurately, so there's less (no) need for manually selecting a theme in recording settings (or user account settings) anymore. Therefore I'll close this one, again :)
