### ISSUE TITLE
Include details on self hosted embedding ReadMe.

### ISSUE THREAD

**Issue by rjb25** [asciinema/asciinema-server#232]
I suggest modifying [this page](https://asciinema.org/docs/embedding). Have a section "Don't want to rely on asciinema.org?" check out the self hosting section of this [readme](https://github.com/asciinema/asciinema-player/blob/master/README.md)
This would have saved me a LOT of time. I at first did not want to use asciinema after reading that all the embedding examples included asciinema.org. I figure there are others who might end up in my boat and fixing this would save them some hassle.
In addition maybe add this to the FAQ under hosting your own version of asciinema. like:

***Do I need to rely on asciinema.org for hosting?***
No, check out the self hosting section of this [readme](https://github.com/asciinema/asciinema-player/blob/master/README.md)

**Comment by sickill** [comment]
That's a great suggestion, thanks!

**Comment by sickill** [comment]
Readme now links to installation doc on wiki.
