### ISSUE TITLE
Should show 404 instead of other public recording

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema-server#252]
Migrated this issue by @ShalokShalom from https://github.com/asciinema/asciinema-player/issues/51

---

This is my video: https://asciinema.org/a/9vzt60y52krsjye6m9ol6w81t

add &theme=solarized-dark and you get to a different one:
https://asciinema.org/a/9vzt60y52krsjye6m9ol6w81t&theme=solarized-dark

Same as with &speed=2 as well, while ?t=25 work correctly

**Comment by disconnect3d** [comment]
Bump. Is there a workaround for that?
Also it would be nice to have info about themes in the docs.

**Comment by ShalokShalom** [comment]
This is still the case

**Comment by sickill** [comment]
Can't reproduce anymore, must have been fixed during the Ruby->Elixir rewrite.
