### ISSUE TITLE
Document gif generation

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema-server#259]
We should have instructions on generating gif with [asciicast2gif](https://github.com/asciinema/asciicast2gif) in:

- [ ] Share / Embed popup
- [x] when someone requests `https://asciinema.org/a/<recording-id>.gif` URL.

**Comment by stapelberg** [comment]
https://github.com/asciinema/asciinema-server/issues/171#issuecomment-402264869 also references termtosvg. Should we re-open issue #171, track that suggestion in this issue’s list, or file a new issue altogother? I’d hate to see that fall through the cracks.
