### ISSUE TITLE
Variable line height

### ISSUE THREAD

**Issue by peterbrittain** [asciinema/asciinema-server#282]
First off, I'd just like to say thanks.  Your service is brilliant!  Now on to the suggestion...

Terminals use different line spacing, but this isn't reflected in the terminal player even though you record the details of the terminal that you recorded the asciicast on.  For example, if I record this (https://asciinema.org/a/123683) in rxvt-unicode-256color, I see no blank space between the lines on the terminal.  However, when I then play it back on asciinema, the line spacing is different and now you see the black bands (as per the public asciicast).

Is it possible to tweak the style of the player based on the terminal it was recorded on to change the line spacing?  I've mocked something up by simply editing the "line" height in the CSS and got pretty close to what I was hoping for:

![qrencode](https://user-images.githubusercontent.com/4748877/29077600-64b7a326-7c50-11e7-854a-f80ebc0fcee3.png)

**Comment by sickill** [comment]
Hey @peterbrittain! I love your asciicasts!

This is known problem to me, and what you're suggesting makes much sense. I don't think the recorder will ever be able to detect line height of the terminal, but this could be easily added to the player as an option, and then to recording/user settings page on asciinema.org.

**Comment by peterbrittain** [comment]
Thank you!  Together we can persuade the world that terminals are the future...  :-)
Agree that you'll struggle to find the actual terminal type-setting configuration, so I'd be perfectly happy with a player option instead, especially if it was available as a setting for the asciicast.

**Comment by sickill** [comment]
We now have an option in asciinema server to set custom line height per recording which can be done for recordings with blocks in them like the one you linked.

I've set line height to 1.1 for your recording already, looks good now:

![image](https://user-images.githubusercontent.com/17589/229778956-8fa0d9e9-6eff-4270-b286-e94f6b99e994.png)

You can tweak that here https://asciinema.org/a/123683/edit if you'd like.
