### ISSUE TITLE
[Feature Request] Add Support for Nerd Fonts

### ISSUE THREAD

**Issue by YonatanAhituv** [asciinema/asciinema-server#290]
I personally use a Nerd Font (Meslo Nerd Font Complete), which includes a ton of icons from Font Awesome and Powerline. However, when recording to Asciinema, most of the icons don't appear. Is it possible for Nerd Font Support?

**Comment by vakaobr** [comment]
+1 on that

**Comment by vjunior1981** [comment]
+1 on that

**Comment by LoudSoftware** [comment]
👍 Same here, it would be great!

**Comment by MatiMenich** [comment]
🙏 Please, it would be awesome!

**Comment by williamcanin** [comment]
Add [Symbols Nerd Font](https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/Symbols-2048-em%20Nerd%20Font%20Complete.ttf) this would help a lot for those who use Glyph from Nerd Font.

**Comment by gabrielmathias** [comment]
It's 2020! I support this request. NerdFonts would be awesome!

**Comment by eug-vs** [comment]
+1, it really sucks when icons don't display and it can screw the whole recording quality

**Comment by tddschn** [comment]
Any update on this?

**Comment by jayp0521** [comment]
+1

**Comment by trilin6** [comment]
+1

**Comment by ranelpadon** [comment]
It's 2023 now and Nerd Fonts are quite popular. Hopefully, you'll include support for it. :)

**Comment by sickill** [comment]
I've implemented support for Nerd Fonts (opt-in, for each uploaded recording) in #412. It brings Fira Code and JetBrains Mono variants for start. I'd rather avoid including every single Nerd Font variant people use in the wild, so let's see first if we can get by with these 2. In the end people request Nerd Font support mostly for icons/symbols, not for specific font faces.

I wonder about the Symbols variant though - https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/NerdFontsSymbolsOnly/complete - is this just symbols, no glyphs? So like e.g. "Fira Code Nerd Font Complete" minus "Fira Code"?

**Comment by sickill** [comment]
Nerd Font support is now live on asciinema.org

![image](https://user-images.githubusercontent.com/17589/229781586-fa781c32-266c-46b2-8bfe-16e45ca0c1b4.png)
