### ISSUE TITLE
Add ability to set idle time limit in Asciinema server link

### ISSUE THREAD

**Issue by jjlin** [asciinema/asciinema-server#293]
Is there a way to set the web player's `idle-time-limit` option from an Asciinema server link? That is, something like

    <a href="http://asciinema.example.com/a/1?idle_time_limit=2" target="_blank">
      <img src="http://asciinema.example.com/a/1.png"/>
    </a>

In some contexts, it's not possible to embed the web player directly (e.g., README.md or various wiki systems), but it would still be nice to be able to control this parameter for recordings you don't own. And anyway, it seems like most of the other web player options are customizable via query params already.

**Comment by sickill** [comment]
This hasn't been added to the params supported by the server, but it's good idea to add it. Thanks for bringing this up 👍

**Comment by sickill** [comment]
Good news! This is now available both as query parameter (see `idleTimeLimit` / `i` here https://asciinema.org/docs/embedding) as well as a permanent setting for each asciicast.
