### ISSUE TITLE
asciinema-server docker installation process fails with ERROR: Service 'web' failed to build: Unknown flag: from

### ISSUE THREAD

**Issue by FlyinFistOfJuda** [asciinema/asciinema-server#298]
Hello, i'm following the guide on...
https://github.com/asciinema/asciinema-server/blob/develop/docs/INSTALL.md

for installing the asciinema-server. Repeatedly i'm stuck at following point:

```
Bundle complete! 53 Gemfile dependencies, 88 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into `./vendor/bundle`
Post-install message from httparty:
When you HTTParty, you must party hard!
 ---> e362e9562376
Removing intermediate container af4edb5e2665
Step 33/88 : COPY --from=0 /app/vt/main.js /app/vt/
ERROR: Service 'web' failed to build: Unknown flag: from
```
...and that's it.

Error `ERROR: Service 'web' failed to build: Unknown flag: from` is repeated when executing ` docker-compose run --rm web mix phx.gen.secret`.

Any ideas what i may be doing wrong?

**Comment by sickill** [comment]
You need newer version of Docker to build it (not sure which one though). `COPY --from=...` wasn't supported in older versions.

**Comment by FlyinFistOfJuda** [comment]
Thanks for the info, i'll give it a try with a newer version.
