### ISSUE TITLE
Documentation for how to run tests

### ISSUE THREAD

**Issue by ajbouh** [asciinema/asciinema-server#305]
Hi, I've been trying to figure out how to run the existing tests before I experiment with making changes, but I can't find any documentation of this anywhere. I see a few commits that refer to making it possible to run tests with docker, and to using the same docker logic for both dev and test, but I haven't seen a specific specific command documented anywhere.

What's the recommended way to run tests locally using docker?

**Comment by ajbouh** [comment]
Experimenting has yielded:

`docker-compose -f dev/docker-compose.yml run phoenix bash -c ' cd assets && npm install && node_modules/webpack/bin/webpack.js --mode development && cd .. && mix deps.get && MIX_ENV=test mix deps.get && mix test'`

**Comment by sickill** [comment]
You figured it out quite well :)

You should be able to run tests on your local machine, outside Docker like this:

1. Fetch Elixir deps

    `mix deps.get`
    `cd assets`
    `npm install`

2. Build assets (this is optional for running tests)

    `node_modules/webpack/bin/webpack.js --mode development`

3. Run Elixir tests

    `cd ..`
    `mix test`

There's also old Rails app test suite which covers some legacy code (which soon will be re-implemented in Elixir), and to run it do this:

1. Fetch Ruby deps

    `bundle install`

2. Run Rails tests

    `bundle exec rake`

**Comment by sickill** [comment]
Update:

Currently this is what it takes to run the test suite:

```
cd assets
npm install
cd ..
mix deps.get
mix test
```
