### ISSUE TITLE
Service 'rails' failed to build

### ISSUE THREAD

**Issue by ajbouh** [asciinema/asciinema-server#306]
When trying to start dev/docker-compose.yml, I get the following error:

` The command '/bin/sh -c wget --quiet -O /opt/jdk-8u172-ea-bin-b03-linux-x64-18_jan_2018.tar.gz --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' https://download.java.net/java/jdk8u172/archive/b03/binaries/jdk-8u172-ea-bin-b03-linux-x64-18_jan_2018.tar.gz &&     tar xzf /opt/jdk-8u172-ea-bin-b03-linux-x64-18_jan_2018.tar.gz -C /opt &&     rm /opt/jdk-8u172-ea-bin-b03-linux-x64-18_jan_2018.tar.gz &&     update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_172/bin/java 1000' returned a non-zero code: 8`

Looks like the same or similar issue encountered in: https://github.com/asciinema/asciinema-server/issues/260

**Comment by MageMasher** [comment]
oracle changed the url, you have to use a different url.

**Comment by sickill** [comment]
I have just (4 weeks ago) updated this URL (https://github.com/asciinema/asciinema-server/commit/a016895188dee7715af1875a05604cc98b2150ca) and they broke it again... 😞

**Comment by MageMasher** [comment]
It’s ok, I understand that’s kind of out or your hands haha

The annoying part is that it was pointed at the archive! Archives should be immutable... You’d think someone would have asked “before we change this url, how many monthly active downloads do we have?” 

Anyways, I wonder if there is a way to build with the right jdk pre downloaded.

**Comment by sickill** [comment]
Yeah... Anyway, I'm happy to accept PR with fixed URL.

I made this Dockerfile.dev for development purposes, mainly because there's many dependencies at the moment due to migration from Rails to Phoenix (Rails and Elixir/Phoenix deps are needed). The setup will be much simpler when we get rid of Rails completely. Frankly, I am now developing on bare metal, it's just too much hassle with Docker for dev.

**Comment by sickill** [comment]
Service `rails` is no longer part of docker-compose so I'm gonna close it.
