### ISSUE TITLE
Confused with Installation Doc. 

### ISSUE THREAD

**Issue by LurkerX-GitHub** [asciinema/asciinema-server#308]
Follow the documentation step-by-step, and then the installation documentation mentions:

> Set `SECRET_KEY_BASE` to long random string. Run `docker-compose run --rm web mix phx.gen.secret` to obtain one.

So I tried:

```
[root@host asciinema-server]# ls
a2png   config.ru           Dockerfile      lib       priv       spec     vt
app     CONTRIBUTING.md     Dockerfile.dev  LICENSE   public     test
assets  dev                 docs            log       Rakefile   uploads
certs   docker              Gemfile         mix.exs   README.md  vendor
config  docker-compose.yml  Gemfile.lock    mix.lock  script     volumes

[root@host asciinema-server]# docker-compose run --rm nginx mix phx.gen.secret
Starting asciinema_postgres ... done
Starting asciinema_smtp     ... done
Starting asciinema_redis    ... done
Starting asciinema_phoenix  ... done
Starting asciinema_rails    ... done
Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"mix\": executable file not found in $PATH": unknown

```
Of course, I generated the `SECRET_KEY_BASE` with `mix phx.gen.secret` in another place, but is the situation in the above screenshot normal?

**Comment by sickill** [comment]
The proper one is `docker-compose run --rm phoenix mix phx.gen.secret` (not `nginx`). This has already been updated on `develop` branch. I'm going to cut a release soon, so the doc on `master` branch reflects that change.
