### ISSUE TITLE
Config Parameter admin_ids

### ISSUE THREAD

**Issue by Shinzu** [asciinema/asciinema-server#313]
hi,

can you tell for what this config parameter is used:

https://github.com/asciinema/asciinema-server/blob/master/config/cfg.rb#L21

Can this also be set via Env Variable , or must it be set in this file?

greetings

**Comment by Shinzu** [comment]
ok thank you

**Comment by Shinzu** [comment]
i tried it, but it only works if  i give only one id, when i give a second id doesnt work anymore for both id's

**Comment by sickill** [comment]
Oh, hmm. I use with just one so never noticed this bug. That's a trivial fix.

**Comment by sickill** [comment]
I've now changed the way admin users are specified. 

After you upgrade to latest code, you can make user an admin via:

    mix asciinema.admin.add email@example.com

or with docker-compose:

    docker-compose run --rm phoenix mix asciinema.admin.add email@example.com

To remove user from admins list use `asciinema.admin.rm` task.

**Comment by sickill** [comment]
I've updated install doc with new admin section: https://github.com/asciinema/asciinema-server/blob/develop/docs/INSTALL.md#administrative-tasks

**Comment by Shinzu** [comment]
hi,

will try it later , so far thank you for your support and this great project in general.

**Comment by sickill** [comment]
Feel free to reopen if you have any trouble with this.

**Comment by Shinzu** [comment]
defining admin user works as expected , again thank you
