### ISSUE TITLE
Suggestion after url changes

### ISSUE THREAD

**Issue by mathieu-aubin** [asciinema/asciinema-server#314]
I recently noticed, after leaving a browser open for a while and trying to click a link, that the one leading to the [feature section of asciinema.org](https://asciinema.org/explore/featured) was dead and replaced by another url.

[The old featured link](https://asciinema.org/browse/featured) now returns a 404 'not found' as shown below from a [_cURL_](https://curl.haxx.se/) request:

```http
curl -sLkI https://asciinema.org/browse/featured

HTTP/2 404 
server: nginx/1.13.9
date: Sat, 16 Jun 2018 12:01:10 GMT
content-type: text/html; charset=utf-8
content-length: 678
vary: Accept-Encoding
cache-control: max-age=0, private, must-revalidate
x-request-id: 2ksa4g1urtjvhtnit001jeh2

```

The better behavior, mostly for compatibility with already stored version of the site and/or bots, webarchive etc... would be to return a 301 'moved permanently' instead of a 404 'not found'.

As you are using [_Nginx_](https://nginx.org) i would tend to use it instead of changing whatever it is that can be changed to have such effect in your code. It would look something like this

```nginx
rewrite ^/browse(.*) $scheme://$host/explore$1 permanent;
```

You can check out [a demo here](https://test.4ce.ca/browse/featured) - it will also pass query strings

I would also strongly suggest you hide the version of [_Nginx_](https://nginx.org) you are using by adding the following inside nginx.conf's http block:

```nginx
server_tokens off;
```

This will prevent you being an easy target in case of a major security flaw in the [_Nginx_](https://nginx.org) version you are using.

**Comment by sickill** [comment]
Thanks Mathieu! Good catches :)

I've enabled the rewrite + hidden server tokens 👍

**Comment by mathieu-aubin** [comment]
awesome, keep up the good work
