### ISSUE TITLE
docker-compose Failing When Running phoenix setup

### ISSUE THREAD

**Issue by ossie-git** [asciinema/asciinema-server#324]
I've successfully deployed asciinema-server on a number of different setups.  However, I'm currently running into the following error when running:

```
docker-compose run --rm phoenix setup
```

It runs for some time until it reaches the following step where it consistently fails:

```
Step 59/88 : COPY mix.* /app/
 ---> Using cache
 ---> 66e07aca1618
Step 60/88 : RUN mix deps.get --only prod && mix deps.compile
 ---> Running in e532a03ff097
  ...
  uuid 1.1.8
* Getting bamboo (Hex package)
* Getting bamboo_smtp (Hex package)
* Getting briefly (Hex package)
* Getting cowboy (Hex package)
* Getting ex_aws (Hex package)
* Getting exq (Hex package)
* Getting exq_ui (Hex package)
Request failed (:timeout)
If this happens consistently, adjust your concurrency and timeout settings:

    HEX_HTTP_CONCURRENCY=1 HEX_HTTP_TIMEOUT=120 mix deps.get
** (Mix) Package fetch failed and no cached copy available (https://repo.hex.pm/tarballs/exq_ui-0.9.0.tar)
ERROR: Service 'phoenix' failed to build: The command '/bin/sh -c mix deps.get --only prod && mix deps.compile' returned a non-zero code: 1
```

I tried it numerous times including starting over and remove all the docker images and containers but I keep running into this issue

I'm running Docker on Mac OS X (10.13.6) with the latest version of Docker (18.06.1-ce-mac73 (26764)

I also tried exporting the above environment variables but it looks like it doesn't read them from my environment.

Any ideas?  Thanks

**Comment by sickill** [comment]
That looks like timeout when fetching deps from https://hex.pm .
Do you still experience this?

Anyway, you can always pull prebuild image from docker hub:

    docker pull asciinema/asciinema-server:latest

That will avoid whole build, saving time and problems :)

**Comment by ossie-git** [comment]
By the way, is this mentioned anywhere in the documentation?  I would think a lot of users would prefer this over the long build process.  I think it would also involve an updated docker-compose.yml file

**Comment by sickill** [comment]
@ossie-git it's an omsision on my part, I'll fix the docs.
