### ISSUE TITLE
How to disable public registration?

### ISSUE THREAD

**Issue by kyxap1** [asciinema/asciinema-server#325]
I wondered how to disable public registration, but have not found anything better than enabling nginx http-auth on `/login/new`.

**Comment by wouda** [comment]
i have the following in my app.ini:

[service]
DISABLE_REGISTRATION              = true

**Comment by sickill** [comment]
There's not built-in way currently, so blocking the route is good way to do it.
I guess you run your instance just for yourself, but it's on the internet, and you don't want people to create accounts, correct?

**Comment by kyxap1** [comment]
Yes, you're right.

**Comment by aloknnikhil** [comment]
I worked around this by setting up SMTP and registering myself and then disabling SMTP and restarting the containers.

**Comment by sickill** [comment]
There's new config option now, `SIGN_UP_DISABLED=true`, which prevents new people from registering.
