### ISSUE TITLE
Slack does not unfurl asciinema.org link correctly

### ISSUE THREAD

**Issue by MageMasher** [asciinema/asciinema-server#327]
Machine version: MacOS 10.12.6
Slack Version: Version 3.1.0 (App Store)

I copied a public url from the asciinema home page and pasted it in slack, expecting it to unfurl.
Got nothing instead.

<img width="380" alt="screen shot 2018-03-30 at 12 08 25 pm" src="https://user-images.githubusercontent.com/1841038/38146455-a7a73158-3413-11e8-9a95-58f08e9d20f5.png">

I expected the link to unfurl with a preview.

If this is the wrong repo I'll gladly move the issue, just point me to the right place.

**Comment by sickill** [comment]
Fixed.
