### ISSUE TITLE
The images used by share does not respect configured cover frame

### ISSUE THREAD

**Issue by eddiewebb** [asciinema/asciinema-server#329]
Expected Behavior:

Editing the cast to adjust the cover frame is reflected in the social media and sharing links, regardless of when change is made.

Actual Behavior:

It seems that unless you edit the cover image before the first share URL is generated, the image will forever be frame 0.

**Comment by sickill** [comment]
@eddiewebb I implemented SVG preview images, so you can replace `.png` with `.svg` in the URL - you'll get super-sharp image, and with no caching problem like above.
