### ISSUE TITLE
Issues when behind reverse proxy

### ISSUE THREAD

**Issue by arnydo** [asciinema/asciinema-server#334]
If deploying behind a reverse proxy there is some content that will not be loaded due to "mixed active content".

```
Blocked loading mixed active content “http://asciinema.mydomain.com/a/1.json”[Learn More](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)
```

In this case, the NGINX Docker container is sitting behind a Traefik proxy acting as an SSL terminator as well. SSL certificates etc are applied at the proxy and the Traefik container talks to NGINX over port 80. 

I assume this particular URL is being hardcoded based on the .env.production settings for the URL_SCHEME=http setting.

Has anyone else experienced this?

**Comment by sickill** [comment]
Yes, for https setup you want to change it to `URL_SCHEME=https`. Have you tried that?
