### ISSUE TITLE
Your asciinema.org website is down

### ISSUE THREAD

**Issue by g33k247** [asciinema/asciinema-server#335]
Unable to upload terminal sessions all day. Getting these error messages:

~ Asciicast recording finished.
~ Press <Enter> to upload, <Ctrl-C> to cancel.

~ Upload failed: The server is having temporary problems. Try again in a minute.
~ Retry later by running: asciinema upload /tmp/tmpyehrm0li-asciinema.json

In addition, not getting the emails when trying to login to the website--again all day today.

**Comment by typelogic** [comment]
I am able to upload and replay, but i cannot web login because it is not sending a login link to my gmail. I'm a previous user.

**Comment by sickill** [comment]
Problem with Mailgun, I'm working on it.

**Comment by sickill** [comment]
I think it's fixed. Can you confirm @g33k247 @typelogic ?

**Comment by g33k247** [comment]
Still getting:

asciinema: recording finished
asciinema: press <enter> to upload to asciinema.org, <ctrl-c> to save locally
asciinema: upload failed: The server is having temporary problems. Try again in a minute.
asciinema: retry later by running: asciinema upload /tmp/tmpz6k5irgy-ascii.cast

**Comment by g33k247** [comment]
asciinema 2.0.2

**Comment by sickill** [comment]
I have created `upload-error-debug` branch in recorder repo. The only change is that it prints full server response in case of unknown error. Can you try this?

    git clone https://github.com/asciinema/asciinema.git
    cd asciinema
    git checkout -t origin/upload-error-debug
    python3 -m asciinema upload /tmp/tmpz6k5irgy-ascii.cast
    # or: python3 -m asciinema rec

**Comment by g33k247** [comment]
Today it is working!!!!  YAY!!!!

**Comment by typelogic** [comment]
All is working now. My i am using `asciinema 2.0.0` version.
