### ISSUE TITLE
tzdata problem

### ISSUE THREAD

**Issue by jas01** [asciinema/asciinema-server#340]
Hi everyone,

I'm trying to install a ascinema inside a openshift. But with the official docker image (from dockerhub) I get a problem with the tzdata, I'm pretty sure it's related with https://github.com/lau/tzdata/issues/81

So please can you upgrade the dockerhub image with the new version of the library

Thanks

**Comment by sickill** [comment]
tzdata has been upgraded, it's 1.0.3 in the latest docker image.
