### ISSUE TITLE
Add responsive playback support

### ISSUE THREAD

**Issue by bkuhlmann** [asciinema/asciinema-server#343]
## Overview

I've discovered a situation where [embedding](https://asciinema.org/docs/embedding) screencasts won't handle responsive design well.

How difficult would it be to add responsive design support?

## Screenshots/Screencasts

Here is an example of one of my screencasts: [Git Rebase Abbreviations](https://www.alchemists.io/screencasts/git_rebase_abbreviations.html). If you try to resize, you'll notice the video isn't able to dynamically scale to a smaller or larger sizes. Part of this is due to `iframe` usage so maybe I'm using the embedded link incorrectly? If there are tips and tricks, I'd be interested. Example:

![example](https://user-images.githubusercontent.com/50245/63642504-3ee64200-c67d-11e9-8fb7-729cbaf8fecf.gif)

## Environment

- macOS
- iTerm2
- asciinema 2.0.2

**Comment by sickill** [comment]
Yeah, the embedded player uses iframe, and this gets its width on initialization. I'm not sure yet what would it take to make it responsive.

**Comment by bkuhlmann** [comment]
:bow: @sickill, I was looking at the [embedded player](https://github.com/asciinema/asciinema-player) and wondering if that would provide a better alternative solution? I haven't had a chance to investigate that solution yet but it looks like it might achieve what I'm trying to do.

**Comment by sickill** [comment]
Good news! The latest versions of the player is fully responsive and I've updated asciinema.org to use it. It now automatically resize both on asciinema.org and when using the embed script on your own site.

**Comment by bkuhlmann** [comment]
Thanks! Yeah, I saw your blog post earlier and wasn't sure if I needed to update anything on my side of the fence but been playing with this new feature and it's very nice. This is great!
