### ISSUE TITLE
Rename a recording?

### ISSUE THREAD

**Issue by dagett** [asciinema/asciinema-server#346]
How do I rename an uploaded (private) recording from default `untitled` ?

    $ asciinema rec
    $ asciinema upload ...

Then in my profile (Chrome) it is listed as

    You have recorded 1 asciicast
    ...
    untitled private

To post the recording on e.g. Slack it would be useful for it to have a meaningful name.

**Comment by dagett** [comment]
Solved it by recording with a title and uploading again.

    $ asciinema rec -t "Test Demo Nov-08" /tmp/tests-ascii.cast
    $ asciinema upload /tmp/tests-ascii.cast

Add to docs?

(The reason not to upload directly was that I needed to edit the cast first. )

**Comment by sickill** [comment]
When you link your machine to your asciinema.org account as described here https://github.com/asciinema/asciinema#auth you can edit the title on the site.
