### ISSUE TITLE
Login email does not arrive

### ISSUE THREAD

**Issue by teake** [asciinema/asciinema-server#347]
When I tried getting a login token via https://asciinema.org/login/new, I was successfully redirected to https://asciinema.org/login/sent but the email never arrives. Is there some problem with the mail configuration?

**Comment by JacFearsome** [comment]
I am having the same issue...

**Comment by genofire** [comment]
Dito

**Comment by sickill** [comment]
Email delivery issue is usually related to gray listing or spam classification on some email providers. Given it's been a while since the reports and currently it works fine I'm going to close the issue. I'll revisit the email sending config anyway. Feel free to re-open if you still experience this problem.

**Comment by genofire** [comment]
Nope, still not get any mail for my account:
https://asciinema.org/~genofire

**Comment by jrussellfreelance** [comment]
Yes thank you.  I know it was not a spam filter issue.

**Comment by rabas-m** [comment]
I have the same issue. Tried both gmail and other mail servers without luck (I also checked in spam and various folders). I even tried temporary use-and-dispose emails without a spam filter, still no luck. I also tried to ask for the email from different devices and browsers (firefox, chromium for ubuntu, chrome for android).

I will try again tomorrow, to check if it was a temporary server issue.

**Comment by genofire** [comment]
@sickill please reopen this issue and check the logs of your mail-setup

**Comment by preritdas** [comment]
Having the same issue. Tried with various email accounts, and nothing's arriving in spam. I tried multiple times and on different days. Not sure what's going on...

**Comment by roelstappers** [comment]
Same issue here. Using gmail

**Comment by deividgdt** [comment]
Hi, I'm having the same issue.

**Comment by kinderjoga** [comment]
Hello! I have the same issue. Using outlook

**Comment by wpcarro** [comment]
I'm having the same issue with gmail (not in spam), and it's been > 30min

**Comment by denysdovhan** [comment]
I'm having the same problem. Can't sign up with gmail email address. No mails in spam folder.

**Comment by sickill** [comment]
Yeah, so Mailgun, which asciinema.org uses for mail delivery, apparently decided to block us, responding with:

> 421 Domain mg.asciinema.org is not allowed to send: Poor mailing list quality

Investigating.

**Comment by sickill** [comment]
Switched SMTP to Fastmail, initial tests show it's working. Let me know if it resolved the problem for you.

**Comment by deividgdt** [comment]
@sickill Now is working, thanks!

**Comment by roelstappers** [comment]
@sickill works for me too now. Thanks!

**Comment by genofire** [comment]
I recieve the mail with 10h delayed - to auth in 15min ... test it tomorrow again

**Comment by genofire** [comment]
Jippi - i got access after 2 years to my account ;)
(this new mail arriveds direct into spam ... - maybe i have to optimise it)

**Comment by teohhanhui** [comment]
Looks like this has stopped working again?

**Comment by felegy** [comment]
Same issue here.

**Comment by sickill** [comment]
Email delivery on asciinema.org should now be fixed.

**Comment by CITIZENDOT** [comment]
Still not working

**Comment by sickill** [comment]
I'm locking the conversation here as things like this are infra/config issues, and (usually) are not a problem with the codebase itself.

If you're having trouble with login email please contact admin@<asciinema-server-domain> (e.g. asciinema.org) with more details (like email address or username you use for login). Thanks!
