### ISSUE TITLE
smtp connection refused

### ISSUE THREAD

**Issue by 45cali** [asciinema/asciinema-server#357]
I have this deployed locally and when I try and login with my gmail email address it fails and in the logs of the smtp server it says 

```
  275 delivering 1jswqv-00004Q-O0
  275 R: dnslookup for example@gmail.com
  276 T: remote_smtp for example@gmail.com
  276 Connecting to gmail-smtp-in.l.google.com [173.194.193.26]:25 ... failed: Connection refused
  276 LOG: MAIN
  276   H=gmail-smtp-in.l.google.com [173.194.193.26] Connection refused
```

I dont understand why the connection is being refused

**Comment by sickill** [comment]
That would be something related to https://github.com/namshi/docker-smtp , best to open issue there.
