### ISSUE TITLE
Recently uploaded vidoes have corrupted images

### ISSUE THREAD

**Issue by bkuhlmann** [asciinema/asciinema-server#358]
## Overview

Upon uploading a video to the server, it used to be that you could view the associated image (PNG) of the video. Example:

- Without Error
  - [Video](https://asciinema.org/a/343851)
  - [Image](https://asciinema.org/a/343851.png)
- With Error
  - [Video](https://asciinema.org/a/347653)
  - [Image](https://asciinema.org/a/347653.png)

## Screenshots/Screencasts

<img width="934" alt="screen-ZvFD2xVi@2x" src="https://user-images.githubusercontent.com/50245/87610643-229f2980-c6c3-11ea-8fbe-a55090a3c59c.png">

## Steps to Recreate

Click on the *With Error* image mentioned above to recreate.

## Desired Behavior

Would expect to see the image render without error. It's important to note that this doesn't happen with existing videos that have been posted in the past. See the *Without Error* image link to see a working example.

**Comment by sickill** [comment]
Thanks for reporting! Fixed now.
