### ISSUE TITLE
ASCII Cinema Server is timing out

### ISSUE THREAD

**Issue by bkuhlmann** [asciinema/asciinema-server#362]
## Overview

When attempting to load random pages on my profile, I'm finding the server to not respond.

## Steps to Recreate

Try loading any of the following links:

- [Home Page](https://asciinema.org)
- [Random Screencast](https://asciinema.org/a/339564)

These pages will time out. This might be hard to recreate because it's random which links fail....but would expect exceptions in the ASCII Cinema server logs. Been seeing this behavior all day today (Sunday). This might have started happening this weekend but not sure.

## Desired Behavior

Would expect the ASCII Cinema server to not time out when hitting the home page or any random screencast in the collection.

**Comment by sickill** [comment]
Thanks for report. I've noticed a small misconfig on the server recently which I've fixed. Are you still experiencing this, or we can close it?

**Comment by bkuhlmann** [comment]
:bow: @sickill Yes and thanks for getting this fixed -- Will be nice to share screencasts again. I've just confirmed this morning that this is working again.
