### ISSUE TITLE
Support arbitrary user ids to run on OpenShift

### ISSUE THREAD

**Issue by bakito** [asciinema/asciinema-server#371]
By default, OpenShift Container Platform runs containers using an arbitrarily assigned user ID. This provides additional security against processes escaping the container due to a container engine vulnerability and thereby achieving escalated permissions on the host node.

The asciinema-server container can not be started within OpenShift. It fails with the following error:

`[FATAL tini (2)] exec /opt/app/bin/asciinema failed: Permission denied`

As described in the OpenShift documentation, this could be solved by changing the group permissions of the application directories. https://docs.openshift.com/container-platform/4.6/openshift_images/create-images.html

Adding the following command to the Dockerfile  would make the image runnable.
`
RUN chgrp -R 0 /opt/app &&
    chmod -R g=u /opt/app
`

**Comment by bakito** [comment]
Reproduce:

Running the container with an arbitrary user and group 0 should not fail wit permission denied.

`
docker run --rm -u 1001:0 docker.io/asciinema/asciinema-server:latest
Last login: Tue Jan 19 14:28:46 CET 2021 on pts/1
[FATAL tini (8)] exec /opt/app/bin/asciinema failed: Permission denied
`

**Comment by sickill** [comment]
Thanks. I see the problem is caused by the executable `/opt/app/bin/asciinema` having mode `700`.
