### ISSUE TITLE
Broken format using web player on asciinema.org 

### ISSUE THREAD

**Issue by peterbrittain** [asciinema/asciinema-server#384]
When I play this sample (https://asciinema.org/a/45946?autoplay=1) on asciinema.org, it looks like it's missing some characters, or maybe using a font that isn't monospaced.

Downloading and playing on my terminal works fine, though.

I'm using Firefox mobile edition to view the asciicast on an Android device.

**Comment by sickill** [comment]
I've recently upgraded the player on asciinema.org to the latest, [new version](https://blog.asciinema.org/post/smaller-faster/). I don't have android device at hand, but on all other browsers and OSes it looks ok. If you still see weird rendering on Android FF then it must be CSS issue for this particular combo (FF + Android).

**Comment by peterbrittain** [comment]
Still broken on FF +Android, when I just checked.  Can I get any diags to help?

**Comment by neyder** [comment]
I can confirm that on FF any characters to end are not rendered.

Also confirming this is not true on chrome/webkit based browsers.

**Comment by neyder** [comment]
I think this is more like a player issue.

I got the same behavior on FF with embedded on my blog.

Firefox
![imagen](https://user-images.githubusercontent.com/1832457/150675168-0e4ac8ee-99e9-447e-ad4b-1d51ed3ff150.png)

Chrome
![imagen](https://user-images.githubusercontent.com/1832457/150675182-8810bf8a-8084-4a9f-9834-0ed08c276966.png)

From inspecting, i got that <div> container size in FF got a smaller value than in chrome, both has same 80ch on pre, but to render correctly i had to add 20% more ch, so from 80ch goes to 96ch.

**Comment by sickill** [comment]
Do you still see this problem on Firefox? If so, what FF version?

**Comment by peterbrittain** [comment]
Yup.  Still seeing it on FF on Android.  Version is 110.0.1 (Build #2015933339), 43c570380+

**Comment by neyder** [comment]
Also on 
109.0.1 (64-bit) Ubuntu 20.04

It's still the same bug on player.

**Comment by ku1ik** [comment]
It looks like this has been due to the missing support for `ch` CSS unit in FF on Android. According to https://caniuse.com/ch-unit it has been finally implemented in October 2023, so I hope we can finally close this :crossed_fingers:

**Comment by peterbrittain** [comment]
Just upgraded to 121.1.0 (Build #2015996455), 62d5117f79+...  Still have the same misaligned output, I'm afraid.

**Comment by ku1ik** [comment]
Bummer :/ I hoped this was it.

**Comment by ku1ik** [comment]
Can you check how the player here - https://docs.asciinema.org/manual/player/ - renders?

**Comment by peterbrittain** [comment]
Not sure what you want me to test there...  That looks like your docs with different recordings from the original one I flagged as failing (https://asciinema.org/a/45946?autoplay=1).

**Comment by ku1ik** [comment]
There's been several updates to rendering and character alignment recently, which hopefully fixed the issue once and for all :crossed_fingers:

**Comment by peterbrittain** [comment]
All looks good this time!  Thanks for persevering.

**Comment by ku1ik** [comment]
Woohoo! 🎉
