### ISSUE TITLE
Broken IRC webchat link in the footer

### ISSUE THREAD

**Issue by handlerug** [asciinema/asciinema-server#385]
> irc: [#asciinema on freenode](https://kiwiirc.com/nextclient/irc.freenode.net/#asciinema)

It should be considered broken because:
* freenode has long rotated their servers under "new" administration, so I doubt the channel still exists there;
* even if it does, the webchat interface doesn't work with freenode:
<img alt="KiwiIRC 'failed to connect to Freenode' screenshot" src="https://user-images.githubusercontent.com/24986597/140295987-9ce4de50-ec24-42bf-baad-0c0d1569d918.png" width="400">

I'd suggest replacing it with: `<a href="https://web.libera.chat/gamja/#asciinema">#asciinema on libera.chat</a>`. I wanted to send a PR but couldn't find the link in this repository, so I guess it's specific to the hosted instance.

**Comment by sickill** [comment]
This is good idea. I already registered #asciinema on Libera.Chat.

**Comment by sickill** [comment]
Fixed in fb4496edadc7cccdd3e9ba23ddb4a6126266f836
