### ISSUE TITLE
Explore is broken on Firefox ESR, in Debian 10

### ISSUE THREAD

**Issue by ant9000** [asciinema/asciinema-server#387]
Video playback is broken on the Firefox ESR version shipped with Debian 10:
```
Uncaught SyntaxError: expected expression, got '='
```
Apparently the culprit is this line:
```
window.players ||= new Map();
```

Same code on Debian 10 default Chromium is fine.

**Comment by sickill** [comment]
Thanks. Fortunately this is easy to fix.

Which version number your FF ESR is btw?

**Comment by ant9000** [comment]
> Thanks. Fortunately this is easy to fix.

Great :-)
 
> Which version number your FF ESR is btw?

It's 78.15.0 ESR.

**Comment by sickill** [comment]
I believe I fixed it. Let me know otherwise.
