### ISSUE TITLE
[Bug] One recording seems to be broken, showing actual text from the initial frame

### ISSUE THREAD

**Issue by AnubisSec** [asciinema/asciinema-server#391]
[https://asciinema.org/a/289353](https://asciinema.org/a/289353)

The link above was a working recording for two years, and is now just showing the text from the initial frame and that's it. Any way to recover this on the backend? 

Note: I don't have access to the original recording anymore.

**Comment by sickill** [comment]
Thanks for reporting. I released the fix now.
