### ISSUE TITLE
Font problem

### ISSUE THREAD

**Issue by Edo78** [asciinema/asciinema-server#395]
Hi, I'm using zsh with the Powerlevel10k theme and I installed the recommended font: "Meslo Nerd Font patched for Powerlevel10k"
Sadly when I try to record my terminal the prompt looks this way https://asciinema.org/a/3evJyXCBjMUooGHGY4RdfHGR6

I tried to look for a solution but I can't figure it out, can you help me?

**Comment by MrWormHole** [comment]
had the same problem : (

**Comment by sickill** [comment]
Solution is coming in #412.

**Comment by sickill** [comment]
Nerd Font support is now live on asciinema.org

I've updated terminal font family setting on the recordings linked above already, they look pretty good now I think.

![image](https://user-images.githubusercontent.com/17589/229781586-fa781c32-266c-46b2-8bfe-16e45ca0c1b4.png)

**Comment by sickill** [comment]
![image](https://user-images.githubusercontent.com/17589/229782310-7e4f6d92-13ae-4a02-8464-da40c12f4d62.png)
