### ISSUE TITLE
asciinema/asciinema-server ERROR (RuntimeError) connect raised KeyError exception: key :password not found

### ISSUE THREAD

**Issue by papan2012** [asciinema/asciinema-server#400]
Greetings

After multiple failed install tried, following the [installation guide](https://github.com/asciinema/asciinema-server/wiki/Installation-guide), looking through forum topis and other online resources, I'll just ask here.

Currently it's full vanilla install, so defaults almost everywhere, apart from .env.production file and fix for postgres [issue 398](https://github.com/asciinema/asciinema-server/issues/399)

My .env.production
```
URL_SCHEME=http
URL_HOST=myurl
URL_PORT=80
SECRET_KEY_BASE=MYSECRETREMOVED
DATABASE_URL=postgresql://postgres@postgres/postgres
MAILNAME=localhost

```

All of the docker containers are running except the "asciinema/asciinema-server"
```
** (RuntimeError) connect raised KeyError exception: key :password not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (elixir 1.12.1) lib/keyword.ex:420: Keyword.fetch!/2
    (postgrex 0.15.5) lib/postgrex/protocol.ex:722: Postgrex.Protocol.auth_md5/4
    (postgrex 0.15.5) lib/postgrex/protocol.ex:579: Postgrex.Protocol.handshake/2
    (db_connection 2.2.2) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

```

So, how do I fix his asciinema/asciinema-server error and make it all work?

Thx in advance

**Comment by jeffh-cloudflare** [comment]
Does this issue persist even after what I suggested in #399 ?

You mentioned my previous issue #398 - which I accidently closed - I replaced it with #399.

**Comment by Adito5393** [comment]
Have a look at the [DB docs](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING) & you will see that you can add the password: `user[:password]`. So instead of the `POSTGRES_HOST_AUTH_METHOD: trust` you can just use a password and add it to the `DATABASE_URL` & see the [Postgres's docker page](https://hub.docker.com/_/postgres/) for what env vars you need.

**Comment by jeffh-cloudflare** [comment]
OK - everything else in the configuration either has in-line comments or the ascii-cinema server documentation is solid - with the exception of the Postgres configuration. It might be a good idea to at least add a reference similar to the other containers such that someone who's not familiar with Postgres can get everything up and running easily. As I mentioned in #399 , a single line added to the docker-compose.yml, along with the rest of the existing documentation makes it a breeze to deploy. It could be made even easier. That's all I'm saying.

**Comment by Adito5393** [comment]
Indeed, I see that there is already PR #394 with the `POSTGRES_HOST_AUTH_METHOD=trust` addition.

**Comment by sickill** [comment]
Thanks guys, I now merged the above PR which should make things easier.

**Comment by ku1ik** [comment]
FYI I've put the new docker-compose.yml template in the new self-hosting quick-start guide: https://docs.asciinema.org/manual/server/self-hosting/quick-start/
