### ISSUE TITLE
Thumbnail missing colors

### ISSUE THREAD

**Issue by rsteube** [asciinema/asciinema-server#401]
Not that it matters but seems the `svg` thumbnail is missing some colors.

[thumbnail](https://asciinema.org/a/533283.svg):
![533283](https://user-images.githubusercontent.com/9090290/199074595-d409c2bb-d8b9-4b1f-a476-219a6fe8a564.svg)

[player](https://asciinema.org/a/533283):
![533283](https://user-images.githubusercontent.com/9090290/199074657-d9e5d8fc-e80c-4aad-9b4b-a696b5f90dfb.png)

**Comment by sickill** [comment]
Thanks for reporting. The fix is live on asciinema.org now.
