### ISSUE TITLE
visual glitches in PNG and SVG when using `▄` character

### ISSUE THREAD

**Issue by philschatz** [asciinema/asciinema-server#413]
Thanks for a great recording/playback tool! It's much nicer than posting GIFs for terminal recordings.

I noticed that in some cases the ASCII characters do not line up properly in the PNG and that the font adds additional padding around the `▄` character. 

The issue I am running into is that I use `▄` to show 2 "pixels" with different colors. Unfortunately, that results in several graphical glitches on the web and is even weirder in the PNG screenshot. See example below:

# Screencasts

Here is a screenshot of the "glitchy" SVG:

[![Game Demo: Skipping Stones to Lonely Homes (small pixels)](https://user-images.githubusercontent.com/253202/42069184-50a01bac-7b1e-11e8-8cdd-2cf5fd9862fd.png)](https://asciinema.org/a/i1NFHEiodvDBQlx5mvKIWw3yV)

Here is the mangled PNG screenshot:

[![Game Demo: Skipping Stones to Lonely Homes (small pixels)](https://asciinema.org/a/i1NFHEiodvDBQlx5mvKIWw3yV.png)](https://asciinema.org/a/i1NFHEiodvDBQlx5mvKIWw3yV)

And here is an example of using ` ` (space) instead, which works but results in a 4x larger recording:

[![Game Demo: Skipping Stones to Lonely Homes (large pixels)](https://asciinema.org/a/mvHT4Btkpj49GzN8fawsUgCTX.png)](https://asciinema.org/a/mvHT4Btkpj49GzN8fawsUgCTX)

I will keep using a ` ` for my demos and recordings (more are at https://github.com/philschatz/puzzlescript-cli) but thought I would post in case others are running into similar issues.

**Comment by sickill** [comment]
There's new option on asciicast settings page now - **Terminal line height**:

![image](https://user-images.githubusercontent.com/17589/229779943-e7308964-4311-4ec8-9256-689c15466b09.png)

I've set it to 1.1 on @philschatz's recording, and to 1.2 on the mentioned featured recording. IMHO they look pretty good now.

**Comment by dimo414** [comment]
Cool! https://asciinema.org/a/i1NFHEiodvDBQlx5mvKIWw3yV looks much better than the screenshots above, though there are still some artifacts. However https://asciinema.org/a/423213 still has clearly visible artifacts.

![Screenshot of i1NFHEiodvDBQlx5mvKIWw3yV](https://user-images.githubusercontent.com/1885701/229917512-c481acd8-12cc-4d28-9946-183b04b01ed6.png)

![Screenshot of 423213](https://user-images.githubusercontent.com/1885701/229917845-99374db2-02d8-4064-93f2-e243dcca68f4.png)

**Comment by sickill** [comment]
Yeah, there are still the vertical lines in the first one. This is not related to line height but likely to text spacing in a browser. Not sure if can be fixed without reimplementing the renderer with canvas...

The second one looks fine on my machine (Firefox on Arch Linux):

![image](https://user-images.githubusercontent.com/17589/230025350-c730b644-dfbd-4a95-a99b-357456d2d8ac.png)

I guess there are text rendering differences between platforms/browsers that it would be hard to completely mitigate.

**Comment by sickill** [comment]
The above screenshot was for line height 1.2 that I set on the recording earlier.
I've now adjusted it to 1.15, let me know if it looks fine for you now.

**Comment by dimo414** [comment]
Yeah unfortunately still seeing artifacts (I'm using Chrome on Windows, fwiw).
