### ISSUE TITLE
Login e-mails are missing "Date" headers

### ISSUE THREAD

**Issue by jwodder** [asciinema/asciinema-server#414]
The e-mails sent by asciinema.org when one wishes to log in lack a "Date" header.  This violates [RFC 5322](https://www.rfc-editor.org/rfc/rfc5322.html), which states in [section 3.6](https://www.rfc-editor.org/rfc/rfc5322.html#section-3.6): "The only required header fields are the origination date field and the originator address field(s)" (and [section 3.6.1](https://www.rfc-editor.org/rfc/rfc5322.html#section-3.6.1) establishes that the "origination date field" is the one with the field name "Date").  It even violates the old [RFC 822](https://www.rfc-editor.org/rfc/rfc822) standard that stood for decades, which states in [section 4.1](https://www.rfc-editor.org/rfc/rfc822#section-4.1) "Creation time, author id & one address required".

**Comment by sickill** [comment]
This should be fixed now. Please confirm when you have a chance. Thanks in advance!

**Comment by jwodder** [comment]
Confirmed; the "Date" header is now present.

**Comment by sickill** [comment]
Great :tada:

**Comment by jwodder** [comment]
The "Date" header is missing from login e-mails again.

**Comment by ku1ik** [comment]
Hey @jwodder, thanks for the report. I've redeployed to asciinema.org with a fix  - explicitly adding `Date` header to outgoing messages in case mailservers don't add it when it's missing. All my email accounts are on servers which apparently fill in the missing `Date` so I can't verify if the fix actually works. Can you confirm it works for you now?

**Comment by jwodder** [comment]
The "Date" header is now present again.

**Comment by ku1ik** [comment]
Fixed with https://github.com/asciinema/asciinema-server/commit/779220a433a7a124056314838cfe7135f5e8cf5d , hopefully for good.
