### ISSUE TITLE
not getting login email

### ISSUE THREAD

**Issue by dixler** [asciinema/asciinema-server#416]
Hi. Greatly appreciate the service you guys provide :pray:. I've recently just started having difficulty getting the login link to my account as it's not showing up in my inbox nor spam.

My user is:
```typescript
const name = "kyle";
const domain = "pulumi.com";
const username = `${name}@${domain}`;
```

**Comment by sickill** [comment]
Hey Kyle. I've recently noticed problems with email delivery. It seems our free Sendgrid plan is not enough anymore....

asciinema.org is a free service, a non-profit org, so there's no budget for things like paid email service plan. Given that I'm looking into switching to some other provider where free tier is more generous than Sendgrid's 100 emails/day.
