### ISSUE TITLE
Add RestructuredText Syntax to Share button menu

### ISSUE THREAD

**Issue by MacHu-GWU** [asciinema/asciinema-server#423]
Since Asciinema is a Python project and RestructuredText is the official language for documentation, maybe we should add a REST link to the share button in ``https://asciinema.org/a/...``?

The syntax should be:

```
.. image:: https://asciinema.org/a/${record_id}.svg
    :target: https://asciinema.org/a/${record_id}
```

**Comment by ku1ik** [comment]
Thanks for the idea. RestructuredText is nowhere near as popular as Markdown and therefore I believe it's something only a tiny fraction of users would expect/use. And btw, asciinema is no longer a Python project.
