### ISSUE TITLE
hot to change default font

### ISSUE THREAD

**Issue by XIYO** [asciinema/asciinema-server#425]
Hello, Asciiinema community.
I'm a non-English speaking user, so I've used translation. Please excuse any rudeness in my tone.

I've searched and read through issues based on the default font but couldn't find any record similar to my situation. I'm self-hosting using Docker.

Is there an option to set a different font as the default font?

**Comment by ku1ik** [comment]
Hi,

Right now there's no global setting for that, but I think it's actually a quite good idea to implement this :+1:

Btw, as a non-English speaker never apologize for your English skills :)

**Comment by XavierChanth** [comment]
+1 on this, would like to set my default to a nerd font, since many of my tools use nerd font symbols in them.

**Comment by ku1ik** [comment]
@XavierChanth would you like to set a default font for your user account, or for the whole self-hosted instance of asciinema server? Both seems like good ideas to me anyway :)

**Comment by XavierChanth** [comment]
> @XavierChanth would you like to set a default font for your user account, or for the whole self-hosted instance of asciinema server? Both seems like good ideas to me anyway :)

For my user account

**Comment by ku1ik** [comment]
I've just deployed #431 (plus few tweaks). Set your default font here: https://asciinema.org/user/edit
