### ISSUE TITLE
exec format error docker-compose on raspberry pi

### ISSUE THREAD

**Issue by SpearsonWa83643** [asciinema/asciinema-server#428]
using the yml file provided in https://docs.asciinema.org/manual/server/self-hosting/quick-start/ 
asciinema does not run on aarch64 raspberry pi:

Attaching to asciinema_container_postgres_1, asciinema_container_asciinema_1
asciinema_1  | exec /sbin/tini: exec format error

**Comment by ku1ik** [comment]
Ah, right, we need to modify the publish workflow (https://github.com/asciinema/asciinema-server/blob/develop/.github/workflows/publish.yml) to build for aarch64.
