### ISSUE TITLE
Memory leak on v20231217

### ISSUE THREAD

**Issue by dmitry-j-mikhin** [asciinema/asciinema-server#429]
I have a small VDS with 1GB of memory (https://asciinema.tw1.ru). I installed asciinema-server v20231217 for personal use. This server has no real load, several requests per day. But every 2 days OOM occurs:
```
Jan 26 18:06:40 2430241-cu30781.twc1.net kernel: Out of memory: Killed process 1109 (beam.smp) total-vm:1665272kB, anon-rss:457200kB, file-rss:0kB, shmem-rss:93584kB, UID:1000 pgtables:1252kB oom_score_adj:200
Jan 28 13:37:05 2430241-cu30781.twc1.net kernel: Out of memory: Killed process 14114 (beam.smp) total-vm:1679664kB, anon-rss:458068kB, file-rss:0kB, shmem-rss:93648kB, UID:1000 pgtables:1284kB oom_score_adj:200
Jan 30 10:21:24 2430241-cu30781.twc1.net kernel: Out of memory: Killed process 25835 (beam.smp) total-vm:1665368kB, anon-rss:468296kB, file-rss:0kB, shmem-rss:93584kB, UID:1000 pgtables:1264kB oom_score_adj:200
```
The memory usage graph looks like this:
![image](https://github.com/asciinema/asciinema-server/assets/41896087/a7675932-1b93-48ba-a978-5f99dac9f229)

**Comment by ku1ik** [comment]
Thanks for the report. Great that you have the graph, this indeed looks like a leak. I'll try to reproduce that locally.

**Comment by dmitry-j-mikhin** [comment]
@ku1ik thanks for the feedback and for this wonderful project. If you need more information, logs, etc. I can also provide.

**Comment by jiriks74** [comment]
I'm currently use the `latest` tag in docker so I don't know what exact version I'm on.

But I can confirm that this indeed happens. I've been running the server for about 4 days now and I've noticed the memory usage steadily climbing. I've restarted the container one time to see if it was just a fluke but the memory usage is still climbing like before. I'll probably make a cron job to restart it at midnight every day to get around this until it's patched.

Also: there's no usage at all. I have a single account on this instance, here are no recordings (apart from the welcome one), no recordings are shared so no websites are loading them and I haven't used it for about 2 days now but it's still going up.

Here's my graph:
![image](https://github.com/asciinema/asciinema-server/assets/54378412/6da23918-0d94-457f-b97f-b618a1883f8a)

If you're interested I can make some tests, etc., as it's a personal instance where downtime won't annoy anyone.

**Comment by jiriks74** [comment]
I just modified my view so that I can filter containers more easily and I also found a way to capture non-visibile parts of a website in Firefox (the built in screenshot tool is still broken) so here's a better screenshot. You can also see the network usage to have an idea of how much this instance is not used.

![asciinema-memory_leak](https://github.com/asciinema/asciinema-server/assets/54378412/a4fa3e18-60d3-4201-abd1-228353a77eae)

> [!Note]
> If you see multiple containers names `asciinema-asciinema-1` it means that there was a container recreation/restart. When I recreate/restart the container some stats get a different ID. It's still the same thing.

**Comment by ku1ik** [comment]
Does the mem usage grow indefinitely, or does it top at some value, and go down?

**Comment by ku1ik** [comment]
I can observe similar behavior on asciinema.org:

![image](https://github.com/asciinema/asciinema-server/assets/17589/785b15a4-e73b-4dff-8cc3-a452832f76d0)

**Comment by jiriks74** [comment]
> Does the mem usage grow indefinitely, or does it top at some value, and go down and the up again?

So far it's indefinitely until I restart it.

**Comment by dmitry-j-mikhin** [comment]
> So far it's indefinitely until I restart it.

Or until OOM kills the process eating up all the memory)

**Comment by dmitry-j-mikhin** [comment]
These are my 30d graphs::
![image](https://github.com/asciinema/asciinema-server/assets/41896087/4bc39888-f017-41a8-a2af-06aeebfd476b)

**Comment by ku1ik** [comment]
Thanks. Yeah, the problem is definitely there. I'm trying to pinpoint it now.

**Comment by jiriks74** [comment]
I see that about the time that the `v20231217` version was reported the admin dashboard was added:

> added admin console endpoint in port 4002, with [Phoenix LiveDashboard](https://github.com/phoenixframework/phoenix_live_dashboard/) at http://localhost:4002/dashboard

https://github.com/asciinema/asciinema-server/releases/tag/v20231216

Maybe that could be the culpruit?

**Comment by ku1ik** [comment]
I think it's the built-in prometheus endpoint (`http://IP:9568/metrics`), which when not queried accumulates aggregated data in ETS table.

**Comment by ku1ik** [comment]
That's likely it: https://github.com/beam-telemetry/telemetry_metrics_prometheus_core/issues/52

**Comment by jiriks74** [comment]
I agree. I exposed the dashboard (recreated the container) and then opened it after a while. The usage has not gone up for an hour now:

![image](https://github.com/asciinema/asciinema-server/assets/54378412/9595f1d8-9e45-418e-9fca-1d3fa6a8f7a9)

> [!Note]
> The memory spike is when I recreated the container to expose port `4002`

**Comment by jiriks74** [comment]
I'll let this run overnight to see how the memory usage behaves and whether opening the dashboard causes the memory to be freed.

**Comment by jiriks74** [comment]
I did a quick test before I went to sleep and after opening the dashboard the memory usage fell down. I can confirm that the *admin* panel feature is what is the cause here.

![image](https://github.com/asciinema/asciinema-server/assets/54378412/1a8cd865-54ae-4248-b2ee-9ff7d4a87257)

> [!Note]
> RSS memory usage didn't go down. This may be caused by my 2GB swap that is 80% free for the majority of time. From reading the issue upstream it looks like the metrics are not flushed from memory until they're loaded by the panel. Since the metrics are static data it would make sense that the Linux would move it to swap.

**Comment by ku1ik** [comment]
I nailed it. This is mem graph from asciinema.org, with the prometheus endpoint disabled. Note the last quarter - flat as table :)

![image](https://github.com/asciinema/asciinema-server/assets/17589/eda2525c-aa1b-40cc-b2a9-72ca2c9c04db)

**Comment by ku1ik** [comment]
I'll release a new version with the fix soon.

**Comment by ku1ik** [comment]
The built-in prometheus endpoint provided the following stats: https://github.com/asciinema/asciinema-server/blob/b3a852d769da24b1360562b443e30ca41de23351/lib/asciinema/telemetry.ex#L48-L76 - so, BEAM VM mem/cpu stats, HTTP request stats, database query stats and background job stats. It didn't have application-level stats like recordings count etc.

I removed it for now to solve the leak, especially that it was undocumented and nobody used it (including me).

I may re-add it in the future, with some more useful stats, and with an explicit config option to enable it.

**Comment by ku1ik** [comment]
> Yeah it was weird for me when I saw it in the logs (admin panel listening on 4002) while docs said there's no admin panel.

Both the dashboard and the `/metrics` endpoint report similar metrics, from the same source.

That admin panel is still there, and it was not the cause of the leak. This panel is a basic dashboard with some metrics, but it doesn't use much any extra resources (not noticeably). It doesn't hurt when it's not used.

The problem was the prometheus `/metrics` endpoint, which I now removed.

**Comment by ku1ik** [comment]
@jiriks74 this one runs on its own port, 9568.

**Comment by ku1ik** [comment]
@jiriks74 the new release is out (docker image), I'm just wrapping up the release notes.

**Comment by ku1ik** [comment]
@jiriks74 https://github.com/asciinema/asciinema-server/releases/tag/v20240515

**Comment by jiriks74** [comment]
Thanks <3

**Comment by jiriks74** [comment]
Using the new release seems to be working. It's been only 15 minutes but I can confirm that I cannot see the memory leak trend as I did before.

<details>
<summary>Old release</summary>

![image](https://github.com/asciinema/asciinema-server/assets/54378412/fc8ad7f2-c6c8-4c6e-a3cf-6023f9bdb061)

</details>

<details>
<summary>New release</summary>

![image](https://github.com/asciinema/asciinema-server/assets/54378412/fad59735-692e-4e4f-9dfd-d4adc0923537)

</details>

> [!Note]
> There is a spike on the second graph but it seems more "normal" usage than just the server eating up RAM gradually.

Both graphs are over an interval of 5 minutes.
