### ISSUE TITLE
[Question] How to connect asciinema-server to PostgreSQL via Unix domain socket?

### ISSUE THREAD

**Issue by yushum** [asciinema/asciinema-server#442]
I couldn't find any documentation regarding how to configure asciinema-server to connect to PostgreSQL using a Unix domain socket. I've searched extensively but couldn't find any relevant questions or discussions on this topic. Could someone please provide guidance on how to achieve this? Thank you!

**Comment by ku1ik** [comment]
Hey. I haven't set it up with UNIX domain socket. But you can try asking on the asciinema forum - https://discourse.asciinema.org/, hopefully someone there can suggest something.
