### ISSUE TITLE
Unable to Upgrade from 2023-11-20 to 2023-12-16 (or later)

### ISSUE THREAD

**Issue by XIYO** [asciinema/asciinema-server#444]
**Describe the bug**
Recorded data cannot be loaded.

**To Reproduce**
1. Upgrade Asciinema server from version `20231120` to `20231216`.
2. Attempt to play any recorded session.
3. Observe that the data fails to load correctly.

**Expected behavior**
I should be able to play recorded `*.cast` files without any issues.

**Screenshots**
![image](https://github.com/asciinema/asciinema-server/assets/27078637/372f551d-c3d4-4803-94f1-91adc11ac41d)

**Versions:**
 - OS: windows 11
 - Browser: edge 124.0.2478.105
 - Asciinema server: 20231120

**Additional context**
Hello,

I used a translation tool for this message. If the context seems off, please let me know, and I will provide a more detailed explanation.

For several months, there were issues with my server, preventing me from upgrading the Asciinema server. The repairs were completed yesterday, and I attempted to upgrade the Asciinema server. The upgrade guide in the package suggested simply updating the version information, indicating no additional steps were necessary.

also same issue localhost

**Comment by ku1ik** [comment]
Can you provide server logs of the 500 errors? This should direct us towards the root cause.

**Comment by XIYO** [comment]
It was my mistake. I could immediately identify the error upon reviewing the log.

Since 20231216:
```diff
    volumes:
      - cache:/opt/app/cache
-     - uploads:/opt/app/uploads
+     - uploads:/var/opt/asciinema/uploads
```

It seems the upload directory has changed with the version upgrade.

If I'm not mistaken, the initial Docker Compose setup was specified as `/opt/app/uploads`.
Shouldn't the upgrade guide include instructions to adjust the volume locations?

**Comment by XIYO** [comment]
"The document has changed slightly from the original. There used to be guidance for `/opt/app.cache` in the Compose file, but it's no longer visible. Can the parts that have disappeared from the guidance be removed?"

**Comment by ku1ik** [comment]
Yeah, this path changed, sorry about the omission. I'll make sure it's included in the release notes of the version which changed it.

**Comment by ku1ik** [comment]
Release notes updated: https://github.com/asciinema/asciinema-server/releases/tag/v20231216

**Comment by XIYO** [comment]
Thank you for addressing that.

Regarding the cache mapping I mentioned earlier, it seems that `cache:/opt/app/cache` has either been moved to `/var/opt/asciinema` or has been removed. Shouldn't this part also be mentioned?

**Comment by ku1ik** [comment]
Right, good catch again. The cache moved in 20231120 version from `/opt/app/cache` to `/var/cache/asciinema`. I'll add that to the 20231120 release notes. Thanks!

**Comment by ku1ik** [comment]
Updated: https://github.com/asciinema/asciinema-server/releases/tag/v20231120

**Comment by XIYO** [comment]
I am glad to have been of help. There is one more thing...

[this self-hosted config document](https://docs.asciinema.org/manual/server/self-hosting/configuration/#local-filesystem)

This document does not mention the use of caching internally. We need information for new users.

**Comment by ku1ik** [comment]
True, good idea, will update the doc 👍
